from __future__ import print_function
import random, math
from lammps import IPyLammps
L = IPyLammps()
L.variable("name string funnel_pour")
L.thermo_modify("flush yes")
L.units("si")
L.variable("PI equal 3.141592653589")
L.variable("seed equal 14314")
L.variable("xlo equal 10")
L.variable("xhi equal 40")
L.variable("ylo equal 10")
L.variable("yhi equal 40")
L.variable("zlo equal -20")
L.variable("zhi equal 50")
L.variable("xc equal 25")
L.variable("yc equal 25")
L.variable("zconehi equal 50")
L.variable("zconelo equal 10")
L.variable("zcyllo equal 0")
L.variable("radconelo equal 2")
L.variable("radconehi equal 20")
L.variable("rlo equal 0.25")
L.variable("rhi equal 0.5")
L.variable("dlo equal 2.0*${rlo}")
L.variable("dhi equal 2.0*${rhi}")
L.variable("skin equal ${rhi}")
L.variable("coeffRes equal 0.1")
L.variable("coeffFric equal 0.5")
L.variable("density equal 1.0")
L.variable("EYoung equal 10^5")
L.variable("Poisson equal 2.0/7.0")
L.variable("GShear equal ${EYoung}/(2*(1+${Poisson}))")
L.variable("gravity equal 1.0")
L.variable("reff equal 0.5*(${rhi}+${rlo})")
L.variable("meff equal ${density}*4.0/3.0*${PI}*${reff}^3")
L.variable("min_mass equal ${density}*4.0/3.0*${PI}*${rlo}*${rlo}*${rlo}")
L.variable("max_mass equal ${density}*4.0/3.0*${PI}*${rhi}*${rhi}*${rhi}")
L.variable("kn equal 4.0*${GShear}/(3*(1-${Poisson}))")
L.variable("kt equal 4.0*${GShear}/(2-${Poisson})")
L.variable("a equal (-2.0*log(${coeffRes})/${PI})^2")
L.variable("gamma_n equal sqrt($a*2*${kn}/${min_mass}/(1+0.25*$a))")
L.variable("gamma_t equal ${gamma_n}*0.5")
L.variable("tcol equal ${PI}/sqrt(2*${kn}/${min_mass}-${gamma_n}/4.0)")
L.variable("dt equal ${tcol}*0.05")
L.timestep("${dt}")
L.variable("dumpfreq equal 1000")
L.variable("logfreq equal 1000")
L.newton("off")
L.atom_style("sphere")
L.boundary("p p f")
L.region("boxreg block ${xlo} ${xhi} ${ylo} ${yhi} ${zlo} ${zhi}")
L.create_box("1 boxreg")
L.pair_style("gran/hertz/history ${kn} ${kt} ${gamma_n} ${gamma_t} ${coeffFric} 1")
L.pair_coeff("* *")
L.neighbor("${skin} bin")
L.thermo("${logfreq}")
L.comm_style("brick")
L.comm_modify("mode multi group all vel yes")
L.balance("1.1 shift xyz 20 1.1")
L.fix("bal all balance 10000 1.1 shift xyz 20 1.01")
L.region("insreg cylinder z ${xc} ${yc} 10 30 50 side in units box")
L.${zcyllo}("${zconelo} side in units box open 2 #Top is open")
L.${zconelo}("${zconehi} side in units box open 1 open 2 #Bottom and top are open")
L.region("hopreg union 2 conereg cylreg")
L.fix("grav all gravity ${gravity} vector 0 0 -1")
L.fix("1 all nve/sphere")
L.fix("hopper3 all wall/gran/region hertz/history ${kn} ${kt} ${gamma_n} ${gamma_t} ${coeffFric} 1 region hopreg")
L.fix("ins all pour 2000 1 42424 region insreg diam range ${dlo} ${dhi} dens ${density} ${density}")
L.thermo_style("custom step cpu atoms ke")
L.thermo_modify("flush yes lost warn")
L.run("20000")
L.unfix("ins")
L.run("150000")
L.region("cylreg delete")
L.region("hopreg delete")
L.${zcyllo}("${zconelo} side in units box open 1 open 2 #Bottom & top are open")
L.region("hopreg union 2 cylreg conereg")
L.unfix("hopper3")
L.fix("hopper3 all wall/gran/region hertz/history ${kn} ${kt} ${gamma_n} ${gamma_t} ${coeffFric} 1 region hopreg")
L.run("100000")
